import { createFileRoute } from "@tanstack/react-router";
import { GraduationCap, HeartHandshake, Lock, ScrollText, ShieldCheck } from "lucide-react";

export const Route = createFileRoute("/_auth/responsible-ai")({
  head: () => ({
    meta: [
      { title: "Responsible AI & POPIA — ELFA" },
      {
        name: "description",
        content:
          "How ELFA protects student data under POPIA, supports academic integrity and keeps AI use safe and transparent.",
      },
      { property: "og:title", content: "Responsible AI at ELFA" },
      {
        property: "og:description",
        content: "POPIA compliance, academic integrity and safety commitments for South African students.",
      },
    ],
  }),
  component: ResponsibleAI,
});

const SECTIONS = [
  {
    icon: Lock,
    title: "Your data and POPIA",
    body: [
      "ELFA processes personal information under the Protection of Personal Information Act 4 of 2013 (POPIA). We collect the minimum needed to run your account: your email address, an optional display name and study level, and the study content you choose to send us.",
      "Your chats and saved outputs are stored in your own account and protected by row-level security, so no other user can read them. We do not sell your information or use it for advertising.",
      "You may access, correct or delete your information at any time — delete individual chats or library items in the app, or request full account deletion. You can also lodge a complaint with the Information Regulator (South Africa).",
      "Learners under 18 should get permission from a parent, guardian or school before creating an account, as required by POPIA's rules on children's personal information.",
    ],
  },
  {
    icon: GraduationCap,
    title: "Academic integrity",
    body: [
      "ELFA is a study aid, not a ghostwriter. Every tool is prompted to explain method and reasoning so you can reproduce the work yourself.",
      "Submitting AI-generated text as your own may breach your school, TVET college or university plagiarism policy and can lead to disciplinary action. Always rewrite in your own words and disclose AI assistance where your institution requires it.",
      "ELFA will refuse to help with live tests, exams or assessments you tell us must be unaided.",
    ],
  },
  {
    icon: ScrollText,
    title: "Accuracy and transparency",
    body: [
      "AI can be confidently wrong. ELFA flags uncertainty and never fabricates citations, statistics or sources — but you must still verify facts against your textbook, lecturer or an official source before you rely on them.",
      "You are always talking to an AI, never a human tutor. Answers are generated by a large language model and can differ each time you ask.",
      "Consumer protection matters: ELFA makes no guarantee of marks, pass rates or exam outcomes.",
    ],
  },
  {
    icon: HeartHandshake,
    title: "Safety and wellbeing",
    body: [
      "ELFA does not provide medical, legal or mental-health advice. If you are struggling, please reach out: SADAG mental health line 0800 567 567, Childline South Africa 116, or your institution's student wellness office.",
      "Harmful, hateful or discriminatory requests are refused, in line with section 16(2) of the Constitution and the Equality Act.",
      "Never share ID numbers, addresses, banking details or other people's personal information in a chat.",
    ],
  },
];

function ResponsibleAI() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:py-12">
      <header className="grid grid-cols-[auto_minmax(0,1fr)] items-center gap-4">
        <span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-accent-gradient text-accent-foreground">
          <ShieldCheck className="size-6" />
        </span>
        <div className="min-w-0">
          <h1 className="truncate font-display text-2xl font-bold sm:text-3xl">Responsible AI</h1>
          <p className="text-sm text-muted-foreground">
            How ELFA handles your data, integrity and safety — in plain language.
          </p>
        </div>
      </header>

      <div className="mt-8 space-y-5">
        {SECTIONS.map(({ icon: Icon, title, body }) => (
          <section key={title} className="card-surface p-6">
            <h2 className="flex items-center gap-2 font-display text-lg font-bold">
              <Icon className="size-5 shrink-0 text-primary" />
              {title}
            </h2>
            <div className="mt-3 space-y-3 text-sm leading-relaxed text-muted-foreground">
              {body.map((paragraph) => (
                <p key={paragraph}>{paragraph}</p>
              ))}
            </div>
          </section>
        ))}
      </div>

      <p className="mt-6 text-xs leading-relaxed text-muted-foreground">
        This page is a plain-language summary of how ELFA works, not legal advice. Institutions and
        learners remain responsible for complying with their own policies and applicable South
        African law.
      </p>
    </div>
  );
}
