/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthChatRouteImport } from './routes/_auth.chat'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthLibraryRouteImport } from './routes/_auth.library'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthChatIndexRouteImport } from './routes/_auth.chat.index'
import { Route as AuthChatThreadIdRouteImport } from './routes/_auth.chat.$threadId'
import { Route as AuthToolsToolIdRouteImport } from './routes/_auth.tools.$toolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChatRoute = AuthChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLibraryRoute = AuthLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChatIndexRoute = AuthChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthChatRoute,
} as any)
const AuthChatThreadIdRoute = AuthChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AuthChatRoute,
} as any)
const AuthToolsToolIdRoute = AuthToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthChatRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/library': typeof AuthLibraryRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthChatThreadIdRoute
  '/tools/$toolId': typeof AuthToolsToolIdRoute
  '/chat/': typeof AuthChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthDashboardRoute
  '/library': typeof AuthLibraryRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthChatThreadIdRoute
  '/tools/$toolId': typeof AuthToolsToolIdRoute
  '/chat': typeof AuthChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/auth': typeof AuthRoute
  '/_auth/chat': typeof AuthChatRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/library': typeof AuthLibraryRoute
  '/api/chat': typeof ApiChatRoute
  '/_auth/chat/$threadId': typeof AuthChatThreadIdRoute
  '/_auth/tools/$toolId': typeof AuthToolsToolIdRoute
  '/_auth/chat/': typeof AuthChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/library'
    | '/api/chat'
    | '/chat/$threadId'
    | '/tools/$toolId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/library'
    | '/api/chat'
    | '/chat/$threadId'
    | '/tools/$toolId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/auth'
    | '/_auth/chat'
    | '/_auth/dashboard'
    | '/_auth/library'
    | '/api/chat'
    | '/_auth/chat/$threadId'
    | '/_auth/tools/$toolId'
    | '/_auth/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/chat': {
      id: '/_auth/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthChatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/library': {
      id: '/_auth/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthLibraryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/chat/': {
      id: '/_auth/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthChatIndexRouteImport
      parentRoute: typeof AuthChatRoute
    }
    '/_auth/chat/$threadId': {
      id: '/_auth/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthChatThreadIdRouteImport
      parentRoute: typeof AuthChatRoute
    }
    '/_auth/tools/$toolId': {
      id: '/_auth/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof AuthToolsToolIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthChatRouteChildren {
  AuthChatThreadIdRoute: typeof AuthChatThreadIdRoute
  AuthChatIndexRoute: typeof AuthChatIndexRoute
}

const AuthChatRouteChildren: AuthChatRouteChildren = {
  AuthChatThreadIdRoute: AuthChatThreadIdRoute,
  AuthChatIndexRoute: AuthChatIndexRoute,
}

const AuthChatRouteWithChildren = AuthChatRoute._addFileChildren(
  AuthChatRouteChildren,
)

interface AuthRouteChildren {
  AuthChatRoute: typeof AuthChatRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthLibraryRoute: typeof AuthLibraryRoute
  AuthToolsToolIdRoute: typeof AuthToolsToolIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChatRoute: AuthChatRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthLibraryRoute: AuthLibraryRoute,
  AuthToolsToolIdRoute: AuthToolsToolIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
