/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppResponsibleAiRouteImport } from './routes/_app.responsible-ai'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppChatIndexRouteImport } from './routes/_app.chat.index'
import { Route as AppChatThreadIdRouteImport } from './routes/_app.chat.$threadId'
import { Route as AppToolsToolIdRouteImport } from './routes/_app.tools.$toolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppResponsibleAiRoute = AppResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRoute,
} as any)
const AppChatThreadIdRoute = AppChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppChatRoute,
} as any)
const AppToolsToolIdRoute = AppToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AppChatRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/library': typeof AppLibraryRoute
  '/responsible-ai': typeof AppResponsibleAiRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/tools/$toolId': typeof AppToolsToolIdRoute
  '/chat/': typeof AppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/library': typeof AppLibraryRoute
  '/responsible-ai': typeof AppResponsibleAiRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/tools/$toolId': typeof AppToolsToolIdRoute
  '/chat': typeof AppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/responsible-ai': typeof AppResponsibleAiRoute
  '/api/chat': typeof ApiChatRoute
  '/_app/chat/$threadId': typeof AppChatThreadIdRoute
  '/_app/tools/$toolId': typeof AppToolsToolIdRoute
  '/_app/chat/': typeof AppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/library'
    | '/responsible-ai'
    | '/api/chat'
    | '/chat/$threadId'
    | '/tools/$toolId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/library'
    | '/responsible-ai'
    | '/api/chat'
    | '/chat/$threadId'
    | '/tools/$toolId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/library'
    | '/_app/responsible-ai'
    | '/api/chat'
    | '/_app/chat/$threadId'
    | '/_app/tools/$toolId'
    | '/_app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/responsible-ai': {
      id: '/_app/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/responsible-ai'
      preLoaderRoute: typeof AppResponsibleAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/chat/$threadId': {
      id: '/_app/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AppChatThreadIdRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/tools/$toolId': {
      id: '/_app/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof AppToolsToolIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatThreadIdRoute: typeof AppChatThreadIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatThreadIdRoute: AppChatThreadIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppResponsibleAiRoute: typeof AppResponsibleAiRoute
  AppToolsToolIdRoute: typeof AppToolsToolIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppResponsibleAiRoute: AppResponsibleAiRoute,
  AppToolsToolIdRoute: AppToolsToolIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
